services:
  #  app:
  #    image: book-and-drive-service
  #    build:
  #      context: .
  #    ports:
  #      - "8082:8082"
  #    environment:
  #      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookanddrive
  #      SPRING_DATASOURCE_USERNAME: bookanddrive
  #      SPRING_DATASOURCE_PASSWORD: b00kanddrive!
  #    depends_on:
  #      - postgres
  postgres:
    image: postgres:16
    environment:
      - 'POSTGRES_DB=bookanddrive'
      - 'POSTGRES_PASSWORD=b00kanddrive!'
      - 'POSTGRES_USER=bookanddrive'
    ports:
      - '5433:5432'
    restart: unless-stopped

  # not gonna use it probably
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0
#    container_name: keycloak
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    command: start-dev
#    ports:
#      - "8084:8080"

  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
volumes:
    redis-data:
