services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=bookanddrive'
      - 'POSTGRES_PASSWORD=b00kanddrive!'
      - 'POSTGRES_USER=bookanddrive'
    ports:
      - '5432'
