services:
  postgres:
    image: postgres:16
    environment:
      - 'POSTGRES_DB=bookanddrive'
      - 'POSTGRES_PASSWORD=b00kanddrive!'
      - 'POSTGRES_USER=bookanddrive'
    ports:
      - '5433:5432'
