spring:
  application:
    name: book-and-drive-service
  datasource:
    url: jdbc:postgresql://localhost:5433/bookanddrive
    username: bookanddrive
    password: b00kanddrive!
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/default, classpath:db/migration/tenants
    schema: public

logging:
  pattern:
    correlation: '[%X{traceId:-}-%X{spanId:-}] [%X{tenantId:-}] '
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

multitenancy:
  http:
    header: X-Tenant-Id

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      "service.name": ${spring.application.name}
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 5s
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always

