spring:
  application:
    name: book-and-drive-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/bookanddrive}
    username: ${SPRING_DATASOURCE_USERNAME:bookanddrive}
    password: ${SPRING_DATASOURCE_PASSWORD:b00kanddrive}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration/default, classpath:db/migration/tenants
    schema: public

server:
  port: 8081

logging:
  pattern:
    correlation: '[%X{traceId:-}-%X{spanId:-}] [%X{tenantId:-}] '
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

multitenancy:
  http:
    header: X-Tenant-Id
